import type { FormData } from '../types';

export function getInitialFormData(): FormData {
  return {
    datosGenerales: {
      codigoIdFamilia: '',
      codigoTerritorio: '',
      codigoMicroterritorio: '',
      corregimiento: '',
      direccion: '',
      numeroIdentificacionHogar: '',
      numeroIdentificacionFamilia: '',
      estratoVivienda: '',
      numeroHogaresVivienda: '',
      numeroFamiliasVivienda: '',
      numeroPersonasVivienda: '',
      codigoFicha: '',
      fechaDiligenciamientoFicha: new Date().toISOString().split('T')[0],
      telefonoContacto: '',
      codigoTipoVivienda: '',
    },
    caracteristicasVivienda: {
      materialPredominanteParedes: '',
      descripcionOtroMaterialParedes: '',
      materialPredominantePiso: '',
      descripcionOtroMaterialPiso: '',
      materialPredominanteTecho: '',
      descripcionOtroMaterialTecho: '',
      hacinamiento: '',
      codigoRiesgoAccidenteVivienda: '',
      sitiosInteresFacilAccesoVivienda: '',
      fuentesEnergiaCombustibleCocinar: '',
      observaCriaderosVectores: '',
      observaCriaderosVectoresCercaVivienda: '',
      actividadEconomicaVivienda: '',
      animalesViviendaEntornoInmediato: '',
      descripcionTipoAnimal: '',
      numeroAnimales: '',
    },
    aguaSaneamientoResiduos: {
      principalFuenteAguaConsumoHumano: '',
      descripcionOtraFuenteAguaConsumo: '',
      disposicionExcretas: '',
      otraDisposicionExcretas: '',
      disposicionAguaResidual: '',
      otraDisposicionAguaResidual: '',
      disposicionResiduosSolidos: '',
      otraDisposicionResiduosSolidos: '',
    },
    composicionFamiliar: {
      tipoFamilia: '',
      numeroPersonasFamilia: '',
      familiograma: '',
      codigoResultadoAPGAR: '',
      cuidador: '',
      escalaZARIT: '',
      ecomapa: '',
    },
    gruposPrioritarios: {
      ninosNinasAdolescentes: '',
      gestantes: '',
      adultosMayores: '',
      victimasConflicto: '',
      personasDiscapacidad: '',
      enfermedadesHuerfanas: '',
      enfermedadesTransmisibles: '',
      otrasEnfermedadesTransmisibles: '',
      sucesosVitalesNormativos: '',
      enSituacionVulnerabilidad: '',
    },
    practicasRecursos: {
      practicasCuidadoSaludCriticas: '',
      conAntecedentesEnfermedades: '',
      fuenteAlimentos: '',
      otrasFuentesAlimentos: '',
      habitosVidaSaludable: '',
      recursosSocioemocionalesCuidadoSalud: '',
      practicasCuidadoEntorno: '',
      practicasRelacionesSanasConstructivas: '',
      recursosSocioComunitariosPromocionSalud: '',
      practicasAutonomiaCapacidadFuncionalAdultoMayor: '',
      practicasPrevencionEnfermedadesParaTodos: '',
      practicasSaberesAncestrales: '',
      exigibilidadDerechoSalud: '',
      descripcionAntecedentes: '',
    },
    integrantes: [],
  };
}
